# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "I am provisioning..."
apt-get update
apt-get -y install puppet
grep ^server /etc/puppet/puppet.conf || echo -e "\n[agent]\nserver=thepekimaster\n" |sudo tee -a /etc/puppet/puppet.conf
grep thepekimaster /etc/hosts || echo -e "\n192.168.0.100 thepekimaster\n"|sudo tee -a /etc/hosts
puppet agent --enable
service puppet restart
echo -n "I am done at "
hostname
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "shell", inline: $script
  
  
 config.vm.define "orjatar01" do |orjatar01|
 orjatar01.vm.hostname = "orjatar01"
 end
 
 config.vm.define "orjatar02" do |orjatar02|
 orjatar02.vm.hostname = "orjatar02"
 end
  
end
